name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              uses: actions/checkout@v4
            - name: List files
              run: ls -lsa
            - name: Read file
              run: cat README.md
